{
 "title": "Docker low-level monitoring",
 "description": "Docker monitoring with Prometheus and cExporter",
 "tags": [
  "docker",
  "low-level"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "docker host",
    "query": "label_values(docker_container_memory_usage_bytes, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Running containers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(docker_container_state{image!=\"\", instance=~\"$instance\"} == 2) - 1"
    }
   ]
  },
  {
   "title": "Stopped or restarting containers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(docker_container_state{image!=\"\", instance=~\"$instance\"} >= 3)"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(docker_container_memory_usage_bytes{image!=\"\", instance=~\"$instance\"}) / 1024 / 1024"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "docker_container_cpu_usage_ratio{image!=\"\", instance=~\"$instance\"}",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "docker_container_memory_usage_bytes{image!=\"\", instance=~\"$instance\"}",
     "legendFormat": "{{container_name}}"
    }
   ]
  }
 ]
}